version: 2.1

jobs:
  build:
    docker:
      - image: webpackcontrib/circleci-node10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Set the GIT_HASH env var for use in later steps
          command: |
            echo "Set GIT_HASH to `git log -1 --pretty=%h`"
            echo 'export GIT_HASH=`git log -1 --pretty=%h`' >> $BASH_ENV
      - run:
          name: Install the dependencies
          command: |
            npm install --production
            npm install -g webpack
            npm install -g webpack-cli
      - run:
          name: Install the custom Ethereum extensions
          command: |
            cp ./scratch/gui/index.jsx ./node_modules/scratch-gui/src/lib/libraries/extensions/index.jsx
            cp -R ./scratch/extensions ./node_modules/scratch-vm/src/extensions/custom
            rm ./node_modules/scratch-vm/src/extensions/custom/contracts
            cp -R ./build/contracts ./node_modules/scratch-vm/src/extensions/custom/contracts
            cp ./scratch/vm/extension-manager.js ./node_modules/scratch-vm/src/extension-support/extension-manager.js
      - run:
          name: Build the Scratch React app
          command: |
            cd ./node_modules/scratch-gui
            npm install web3@0.20.3
            webpack --progress --colors --bail

