version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.9
jobs:
  build:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Set the GIT_HASH env var for use in later steps
          command: |
            echo "Set GIT_HASH to `git log -1 --pretty=%h`"
            echo 'export GIT_HASH=`git log -1 --pretty=%h`' >> $BASH_ENV
      - run:
          name: Install the dependencies
          command: |
            npm install --production
            cd ./node_modules/scratch-gui
            npm install
            npm install web3@0.20.3
      - run:
          name: Install the custom Ethereum extensions
          command: |
            cp ./scratch/gui/index.jsx ./node_modules/scratch-gui/src/lib/libraries/extensions/index.jsx
            cp -R ./scratch/extensions ./node_modules/scratch-gui/node_modules/scratch-vm/src/extensions/custom
            # the following is a symbolic link to ../../build/contracts which will not work for this build
            rm ./node_modules/scratch-gui/node_modules/scratch-vm/src/extensions/custom/contracts
            cp -R ./build/contracts ./node_modules/scratch-gui/node_modules/scratch-vm/src/extensions/custom/contracts
            cp ./scratch/vm/extension-manager.js ./node_modules/scratch-gui/node_modules/scratch-vm/src/extension-support/extension-manager.js
      - run:
          name: Build the Scratch React app
          command: |
            cd ./node_modules/scratch-gui
            npx webpack --progress --colors --bail
      - run:
          name: Install Python dependency for AWS CLI
          command: sudo apt-get install python-dev
      - aws-s3/sync:
          from: ./node_modules/scratch-gui/build
          to: 's3://scratch.addisonbrown.com.au/'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          # arguments: |
          #   --acl public-read \
          #   --cache-control "max-age=86400"
          overwrite: true
      - run:
          name: Clear CloudFront
          command: |
            echo "AWS_CLOUDFRONT_DISTRIBUTION_ID set to $AWS_CLOUDFRONT_DISTRIBUTION_ID"
            aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
